### ISSUE TITLE
Nested properties

### ISSUE THREAD

**Issue by DurandA** [mozilla-iot/webthing-node#3]
Is it possible to nest properties? I think that the [Web Thing API](https://iot.mozilla.org/wot/) does not mention it. For example, I want a property gas such as:
```
{
  "gas": {
    "eco2": 400
    "tvoc": 1000
  }
}
```
It would be neat to access nested properties using either */properties/gas/eco2* and */properties/gas/tvoc* or using */properties/gas* and get both values.

One other possible case would be reusing of [Web Thing Types](https://iot.mozilla.org/wot/#web-thing-types), e.g. a composite Thing with a built-in RGB LED:
```
"properties": {
  "led": {
    "type": "onOffColorLight",
    "properties": {
      "on": {"type": "boolean"},
      "color": {"type": "string"}
    }
  }
}
```

**Comment by mrstegeman** [comment]
Currently, nested properties are not supported by the spec. The W3C has been considering it for inclusion as part of a capabilities-based system, rather than using predefined thing types. That system would definitely be much for flexible.

If/when that is included in the spec, I will absolutely update this module with support!

If you'd like to track this issue better, you could file an issue against the spec and we will update it when we have any news: https://github.com/mozilla-iot/wot/issues
