### ISSUE TITLE
Explicit writable properties

### ISSUE THREAD

**Issue by DurandA** [mozilla-iot/webthing-node#5]
The [W3C Thing Description](https://w3c.github.io/wot-thing-description/#property) has a "writable" property field while the [Web Thing API](https://iot.mozilla.org/wot/) does not make it explicit. Should we use OPTIONS to know if a PUT is possible on the property? I think that this module does not have this feature yet.

**Comment by mrstegeman** [comment]
Correct, our Web Thing API does not currently support a writable property, but [we have plans](https://github.com/mozilla-iot/wot/issues/38) for it.

The webthing libraries were built to match the Web Thing API, rather than the W3C Thing Description. Ideally, those will converge in the near future. The webthing libraries will be updated in accordance with each change to the Web Thing API.
